### ISSUE TITLE
Instructions on running code

### ISSUE THREAD

**Issue by faysalhossain2007** [ICSE-2019-AUTOFIX/ICSE-2019-AUTOFIX#5]
Can you share the step-by-step guideline to run (train and evaluate) the model?

**Comment by davidswresearcher** [comment]
Environment Requirements

Python 2.x

Pytorch < 0.5

pip install asttokens


If you want to use Python 3.x and Pytorch >= 0.5, then the following links might be useful:


https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems

https://github.com/pytorch/pytorch/issues/23393



Step 1. Change the input and output paths.

By default, the input path and output path are hard coded to this folder:


/media/BACKUP/ghproj_d/code_summarization



You need to replace that folder into whatever folder you like, say "/path/to"


Let’s say you want to save the trained model and data in “/path/to”, then you can search and replace “/media/BACKUP/ghproj_d/code_summarization” to “/path/to” in the python files (e.g. “main.py” file and “csc/script/github/python_process.py”).


Step 2. Copy the original dataset to “/path/to”

Under the repo’s root folder “ICSE-2019-AUTOFIX”, run the following command to copy the original data to the folder you like:


cp -r csc/dataset/ /path/to/github-python


Step 3. Preprocessing data

Under the repo’s root folder “ICSE-2019-AUTOFIX”, run the following command to preprocess the original data to what we need:


cd csc/script/github/ && python python_process.py


Then back to the root folder “ICSE-2019-AUTOFIX” again, run “main.py” with the argument “preprocess”:


python main.py “preprocess”


This command will transfer the data into the format that the model needs.





if you ever checked the "main.py" file, you should see that it takes three parameters: "preprocess", "train_a2c", and "test_a2c"



The names are pretty self-explainable.

Step 4. Start training

Under the repo’s root folder “ICSE-2019-AUTOFIX”, run the following command with arguments:


python main.py “train_a2c” -1 10 0 text 1 0


The followings are the meanings of the above arguments, you can also find them in the “main.py” and “csc/a2c-train.py” files:


“train_a2c”: To train the model.

“-1”: Epoch to start reinforcement training. Use -1 to start immediately.

“10”: Epoch to stop training.

“0”: Number of epochs to pretrain critic (actor fixed).

“text”: Type of encoder to use. Options are [text|code].

“1”: Attn model or not

“0”: Use CUDA on the listed devices.


In the a2c-train.py file, all of the above parameters are clearly defined.
Step 5. Test the trained model

Under the repo’s root folder “ICSE-2019-AUTOFIX”, run the following command with arguments:


python main.py “test_a2c” text 1 0


The followings are the meanings of the above arguments, you can also find them in the “main.py” and “csc/a2c-train.py” files:


“text”: Type of encoder to use. Options are [text|code].

“1”: Attn model or not

“0”: Use CUDA on the listed devices.


all of the above parameters are clearly defined in the file a2c-train.py file.

**Comment by faysalhossain2007** [comment]
Thanks  a lot for detailed instructions. However, I an issue which I try to bypass by checking the value before assigning to the dictionary: 


Log:

```
Traceback (most recent call last):
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/preprocess.py", line 148, in <module>
    main()
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/preprocess.py", line 121, in main
    dicts['src'] = initVocabulary(opt, 'code', opt.train_src, opt.src_vocab_size)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/data/Tree.py", line 142, in initVocabulary
    genWordVocab = makeVocabulary(opt, name, dataFile, vocabSize)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/data/Tree.py", line 133, in makeVocabulary
    vocab = vocab.prune(size)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/data/Dict.py", line 104, in prune
    newDict.add(self.idxToLabel[i])
KeyError: tensor(11)
failed.

```

I bypass this by validating the value in `lib/Dict.py`

```
    if i in self.idxToLabel:
                 newDict.add(self.idxToLabel[i])
```

In this way, I was able to run the preprocess.py. But when I run the train_a2c, it shows me the following error:


```
Traceback (most recent call last):
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/a2c-train.py", line 338, in <module>
    main()
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/a2c-train.py", line 331, in main
    reinforce_trainer.train(opt.start_reinforce + opt.critic_pretrain_epochs, opt.end_epoch, False, start_time)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/train/ReinforceTrainer.py", line 57, in train
    train_reward, critic_loss = self.train_epoch(epoch, pretrain_critic, no_update)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/train/ReinforceTrainer.py", line 152, in train_epoch
    critic_loss = self.critic.backward(baselines, rewards, critic_weights, num_words, self.critic_loss_func, regression=True)
  File "/opt/sota/ICSE-2019-AUTOFIX-master/csc/lib/model/EncoderDecoder.py", line 675, in backward
    outputs.backward(grad_output)
  File "/home/faysal/anaconda3/envs/dlfix/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/faysal/anaconda3/envs/dlfix/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function CatBackward returned an invalid gradient at index 0 - expected shape [1, 512] but got [1, 1, 512]
failed.

```

^This problem is surely related the shape value that is provided while calculating the backward gradient. But I was thinking as you didn't face this issue, then what is the root cause of this issue. Whether it is due to the bypassing while preprocessing the data or it caused by any other reason.

My conda environment includes:
Python 2.7.15

>>> torch.__version__
'0.4.1.post2'

>>> gensim.__version__
'3.8.3'


Please let me know whether you face this issue or do you have any suggestion to this. Any kind of  help is highly appreciable!

**Comment by nashid** [comment]
@faysalhossain2007 were you able to run the model eventually?

**Comment by faysalhossain2007** [comment]
no not really. I have been stuck at the last error for a while.

**Comment by VSturbo** [comment]
@faysalhossain2007 try pytorch=0.2

**Comment by bazinga-zero** [comment]
> 

pytorch=0.2 is not working on python 2.7, so need to update python version to 3.X. And there is another problem occur.
